innopacks/panel/routes/web.php
<?php
/**
 * Copyright (c) Since 2024 InnoShop - All Rights Reserved
 *
 * @link       https://www.innoshop.com
 * @author     InnoShop <team@innoshop.com>
 * @license    https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
 */

use Illuminate\Support\Facades\Route;
use InnoShop\Panel\Controllers;

Route::get('login', [Controllers\LoginController::class, 'index'])->name('login.index');
Route::post('login', [Controllers\LoginController::class, 'store'])->name('login.store');

Route::middleware(['admin_auth:admin'])
    ->group(function () {
        Route::get('logout', [Controllers\LogoutController::class, 'index'])->name('logout.index');

        Route::get('/', [Controllers\DashboardController::class, 'index'])->name('dashboard.index');

        Route::get('/locale/{code}', [Controllers\LocaleController::class, 'switch'])->name('locale.switch');

        Route::post('/upload/images', [Controllers\UploadController::class, 'images'])->name('upload.images');
        Route::post('/upload/files', [Controllers\UploadController::class, 'files'])->name('upload.files');

        Route::resource('/orders', Controllers\OrderController::class);
        Route::get('/orders/{order}/printing', [Controllers\OrderController::class, 'printing'])->name('orders.printing');
        Route::put('/orders/{order}/status', [Controllers\OrderController::class, 'changeStatus'])->name('orders.change_status');

        Route::resource('/order_returns', Controllers\OrderReturnController::class);
        Route::put('/order_returns/{order_return}/status', [Controllers\OrderReturnController::class, 'changeStatus'])->name('order_returns.change_status');

        Route::resource('/products', Controllers\ProductController::class);
        Route::put('/products/{product}/active', [Controllers\ProductController::class, 'active'])->name('products.active');
        Route::get('/products/{product}/copy', [Controllers\ProductController::class, 'copy'])->name('products.copy');

        Route::resource('/categories', Controllers\CategoryController::class);
        Route::put('/categories/{category}/active', [Controllers\CategoryController::class, 'active'])->name('categories.active');

        Route::resource('/attribute_groups', Controllers\AttributeGroupController::class);

        Route::resource('/attributes', Controllers\AttributeController::class);

        Route::resource('/attribute_values', Controllers\AttributeValueController::class);

        Route::resource('/brands', Controllers\BrandController::class);
        Route::put('/brands/{currency}/active', [Controllers\BrandController::class, 'active'])->name('brands.active');

        Route::resource('/reviews', Controllers\ReviewController::class);
        Route::put('/reviews/{review}/active', [Controllers\ReviewController::class, 'active'])->name('reviews.active');

        Route::resource('/articles', Controllers\ArticleController::class);
        Route::put('/articles/{currency}/active', [Controllers\ArticleController::class, 'active'])->name('articles.active');

        Route::resource('/catalogs', Controllers\CatalogController::class);
        Route::put('/catalogs/{catalog}/active', [Controllers\CatalogController::class, 'active'])->name('catalogs.active');

        Route::resource('/tags', Controllers\TagController::class);
        Route::put('/tags/{tag}/active', [Controllers\TagController::class, 'active'])->name('tags.active');

        Route::resource('/pages', Controllers\PageController::class);
        Route::put('/pages/{page}/active', [Controllers\PageController::class, 'active'])->name('pages.active');

        Route::resource('/customers', Controllers\CustomerController::class);
        Route::get('/customers/{customer}/login', [Controllers\CustomerController::class, 'loginFrontend'])->name('customers.login');
        Route::put('/customers/{customer}/active', [Controllers\CustomerController::class, 'active'])->name('customers.active');

        Route::resource('/customer_groups', Controllers\CustomerGroupController::class);
        Route::get('/social', [Controllers\SocialController::class, 'index'])->name('socials.index');
        Route::post('/social', [Controllers\SocialController::class, 'store'])->name('socials.store');

        Route::get('/analytics', [Controllers\AnalyticsController::class, 'index'])->name('analytics.index');
        Route::get('/analytics/order', [Controllers\AnalyticsController::class, 'order'])->name('analytics_order');
        Route::get('/analytics/product', [Controllers\AnalyticsController::class, 'product'])->name('analytics_product');
        Route::get('/analytics/customer', [Controllers\AnalyticsController::class, 'customer'])->name('analytics_customer');

        Route::get('/locales', [Controllers\LocaleController::class, 'index'])->name('locales.index');
        Route::post('/locales/install', [Controllers\LocaleController::class, 'install'])->name('locales.install');
        Route::get('/locales/{locale}/edit', [Controllers\LocaleController::class, 'edit'])->name('locales.edit');
        Route::put('/locales/{locale}', [Controllers\LocaleController::class, 'update'])->name('locales.update');
        Route::post('/locales/{code}/uninstall', [Controllers\LocaleController::class, 'uninstall'])->name('locales.uninstall');
        Route::put('/locales/{country}/active', [Controllers\LocaleController::class, 'active'])->name('locales.active');

        Route::get('/themes', [Controllers\ThemeController::class, 'index'])->name('themes.index');
        Route::put('/themes/{code}/active', [Controllers\ThemeController::class, 'enable'])->name('themes.active');
        Route::get('/themes/settings', [Controllers\ThemeController::class, 'settings'])->name('themes_settings.index');
        Route::put('/themes/settings', [Controllers\ThemeController::class, 'updateSettings'])->name('themes_settings.update');

        Route::get('/account', [Controllers\AccountController::class, 'index'])->name('account.index');
        Route::put('/account', [Controllers\AccountController::class, 'update'])->name('account.update');

        Route::get('/settings', [Controllers\SettingController::class, 'index'])->name('settings.index');
        Route::put('/settings', [Controllers\SettingController::class, 'update'])->name('settings.update');

        Route::post('/content_ai/generate', [Controllers\ContentAIController::class, 'generate'])->name('content_ai.generate');

        Route::resource('/admins', Controllers\AdminController::class);
        Route::put('/admins/{currency}/active', [Controllers\AdminController::class, 'active'])->name('admins.active');

        Route::resource('/roles', Controllers\RoleController::class);

        Route::resource('/currencies', Controllers\CurrencyController::class);
        Route::put('/currencies/{currency}/active', [Controllers\CurrencyController::class, 'active'])->name('currencies.active');

        Route::resource('/countries', Controllers\CountryController::class);
        Route::put('/countries/{country}/active', [Controllers\CountryController::class, 'active'])->name('countries.active');

        Route::resource('/states', Controllers\StateController::class);
        Route::put('/states/{state}/active', [Controllers\StateController::class, 'active'])->name('states.active');

        Route::resource('/regions', Controllers\RegionController::class);
        Route::put('/regions/{state}/active', [Controllers\RegionController::class, 'active'])->name('regions.active');

        Route::resource('/tax_classes', Controllers\TaxClassController::class);
        Route::resource('/tax_rates', Controllers\TaxRateController::class);

        Route::get('file_manager', [InnoShop\RestAPI\PanelApiControllers\FileManagerController::class, 'index'])->name('file_manager.index');
        Route::get('file_manager/iframe', [InnoShop\RestAPI\PanelApiControllers\FileManagerController::class, 'iframe'])->name('file_manager.iframe');
    });

innopacks/panel/resources/views/articles/form.blade.php
@extends('panel::layouts.app')

@section('title', __('panel/menu.articles'))

<x-panel::form.right-btns />

@section('content')
<form class="needs-validation" novalidate
  id="app-form"
  action="{{ $article->id ? panel_route('articles.update', [$article->id]) : panel_route('articles.store') }}"
  method="POST">
  @csrf
  @method($article->id ? 'PUT' : 'POST')

  <div class="row">
    <div class="col-12 col-md-9">
      <div class="card mb-3">
        <div class="card-header">
          <h5 class="card-title mb-0">{{ __('panel/common.basic_info') }}</h5>
        </div>
        <div class="card-body">
          <div class="accordion accordion-flush locales-accordion" id="data-locales">
            @foreach (locales() as $locale)
            @php($localeCode = $locale->code)
            @php($localeName = $locale->name)
            <div class="accordion-item">
              <h2 class="accordion-header">
                <button class="accordion-button {{ $loop->first ? '' : 'collapsed' }}" type="button"
                  data-bs-toggle="collapse" data-bs-target="#data-locale-{{ $localeCode }}"
                  aria-expanded="{{ $loop->first ? 'true' : 'false' }}" aria-controls="data-locale-{{ $localeCode }}">
                  <div class="wh-20 me-2">
                    <img src="{{ image_origin($locale->image) }}" class="img-fluid">
                  </div>
                  {{ $localeName }}
                </button>
              </h2>
              <div id="data-locale-{{ $localeCode }}"
                class="accordion-collapse collapse {{ $loop->first ? 'show' : '' }}" data-bs-parent="#data-locales">
                <div class="accordion-body">
                  <input name="translations[{{$localeCode}}][locale]" value="{{$localeCode}}" class="d-none">

                  <x-common-form-input title="{{ __('panel/article.title') }}" name="translations[{{$localeCode}}][title]"
                    value="{{ old('translations.' . $localeCode . '.title', $article->translate($localeCode, 'title')) }}"
                    required />

                  <x-common-form-rich-text title="{{ __('panel/article.content') }}" name="translations[{{$localeCode}}][content]"
                    value="{{ old('translations.' . $localeCode . '.content', $article->translate($localeCode, 'content')) }}"
                    required />

                  <x-common-form-textarea title="{{ __('panel/article.summary') }}" name="translations[{{$localeCode}}][summary]"
                    value="{{ old('translations.' . $localeCode . '.summary', $article->translate($localeCode, 'summary')) }}"
                    column="article_summary" generate="true" />

                  <x-common-form-image title="{{ __('panel/article.image') }}" name="translations[{{$localeCode}}][image]"
                    value="{{ old('translations.' . $localeCode . '.image', $article->translate($localeCode, 'image')) }}" />

                  <x-common-form-input title="{{ __('panel/setting.meta_title') }}" name="translations[{{$localeCode}}][meta_title]"
                    value="{{ old('translations.' . $localeCode . '.meta_title', $article->translate($localeCode, 'meta_title')) }}"
                    column="article_title" generate="true" />

                  <x-common-form-input title="{{ __('panel/setting.meta_keywords') }}" name="translations[{{$localeCode}}][meta_keywords]"
                    value="{{ old('translations.' . $localeCode . '.meta_keywords', $article->translate($localeCode, 'meta_keywords')) }}"
                    column="article_keywords" generate="true" />

                  <x-common-form-input title="{{ __('panel/setting.meta_description') }}" name="translations[{{$localeCode}}][meta_description]"
                    value="{{ old('translations.' . $localeCode . '.meta_description', $article->translate($localeCode, 'meta_description')) }}"
                    column="article_description" generate="true" />
                </div>
              </div>
            </div>
            @endforeach
          </div>
        </div>
      </div>
    </div>

    <div class="col-12 col-md-3 ps-md-0">
      <div class="card">
        <div class="card-body">
          <x-common-form-switch-radio title="{{ __('panel/common.whether_enable') }}" name="active" :value="old('active', $article->active ?? true)" />

          <x-common-form-select title="{{ __('panel/article.catalog') }}" name="catalog_id" :value="old('catalog_id', $article->catalog_id ?? 0)"
            :options="$catalogs" key="id" label="name" />

          <x-common-form-input title="{{ __('panel/common.slug') }}" name="slug" :value="old('slug', $article->slug ?? '')"
            placeholder="{{ __('panel/common.slug') }}" column="article_slug" generate="true" />

          <x-panel-form-autocomplete-list name="tag_ids[]"
            :value="old('tag_ids', $article->tags->pluck('id')->toArray() ?? [])" placeholder="{{ __('panel/article.tag_search') }}" title="{{ __('panel/article.tag') }}"
            api="/api/panel/tags" />

          <x-common-form-input title="{{ __('panel/article.position') }}" name="position" :value="old('position', $article->position ?? 0)"
             />

          <x-common-form-input title="{{ __('panel/article.viewed') }}" name="viewed" :value="old('viewed', $article->viewed ?? 0)"
             />

          <x-common-form-input title="{{ __('panel/article.author') }}" name="author" :value="old('author', $article->author ?? '')"
             />
        </div>
      </div>
    </div>
  </div>

  <button type="submit" class="d-none"></button>
</form>
@endsection

@push('footer')
<script>
</script>
@endpush

innopacks/panel/resources/views/articles/index.blade.php
@extends('panel::layouts.app')
@section('body-class', '')

@section('title', __('panel/menu.articles'))
@section('page-title-right')
  <a href="{{ panel_route('articles.create') }}" class="btn btn-primary"><i class="bi bi-plus-square"></i> {{ __('panel/common.create') }}</a>
@endsection

@section('content')
<div class="card h-min-600" id="app">
  <div class="card-body">

  <x-panel-criteria :criteria="$criteria ?? []" :action="panel_route('articles.index')" />

    <div class="table-responsive">
      <table class="table align-middle">
        <thead>
          <tr>
            <td>{{ __('panel/common.id')}}</td>
            <td>{{ __('panel/article.image') }}</td>
            <td>{{ __('panel/article.title') }}</td>
            <td>{{ __('panel/article.catalog') }}</td>
            <td>{{ __('panel/article.tag') }}</td>
            <td>{{ __('panel/common.slug') }}</td>
            <td>{{ __('panel/common.position') }}</td>
            <td>{{ __('panel/common.active') }}</td>
            <td>{{ __('panel/common.actions') }}</td>
          </tr>
        </thead>
        @if ($articles->count())
        <tbody>
        @foreach($articles as $item)
      <tr>
      <td>{{ $item->id }}</td>
      <td><img src="{{ image_resize($item->translation->image ?? '', 30, 30) }}" style="width: 30px; height: 30px" alt=""></td>
      <td>{{ sub_string($item->translation->title ?? '') }}</td>
      <td>{{ $item->catalog->translation->title ?? '-' }}</td>
      <td>{{ $item->tagNames ?? '' }}</td>
      <td>{{ sub_string($item->slug) }}</td>
      <td>{{ $item->position }}</td>
      <td>@include('panel::shared.list_switch', ['value' => $item->active, 'url' => panel_route('articles.active', $item->id)])</td>
      <td>
      <div class="d-flex gap-1">
      <a href="{{ panel_route('articles.edit', [$item->id]) }}">
      <el-button size="small" plain type="primary">{{ __('panel/common.edit')}}</el-button>
      </a>
      <form ref="deleteForm" action="{{ panel_route('articles.destroy', [$item->id]) }}" method="POST" class="d-inline">
      @csrf
      @method('DELETE')
      <el-button size="small" type="danger" plain @click="open({{$item->id}})">{{ __('panel/common.delete')}}</el-button>
      </form>
      </div>
      </td>
      </tr>
      @endforeach
        </tbody>
    @else
        <tbody><tr><td colspan="5"><x-common-no-data /></td></tr></tbody>
        @endif
      </table>
    </div>
    {{ $articles->withQueryString()->links('panel::vendor/pagination/bootstrap-4') }}
  </div>
</div>
@endsection

@push('footer')
   <script>
    const {createApp, ref} = Vue;
    const {ElMessageBox, ElMessage} = ElementPlus;

    const app = createApp({
    setup() {
     const deleteForm = ref(null); 

    const open = (index) => {
     ElMessageBox.confirm(
      '{{ __("common/base.hint_delete") }}',
      '{{ __("common/base.cancel") }}',
      {
      confirmButtonText: '{{ __("common/base.confirm")}}',
      cancelButtonText: '{{ __("common/base.cancel")}}',
      type: 'warning',
      }
    )
    .then(() => {
      const deleteUrl =urls.base_url+'/articles/'+index;
      deleteForm.value.action=deleteUrl;
      deleteForm.value.submit();
    })
    .catch(() => {
    });
   };

    return {open, deleteForm}; 
     }
    });

    app.use(ElementPlus);
    app.mount('#app');
  </script>
@endpush

innopacks/panel/resources/views/order_returns/index.blade.php
@extends('panel::layouts.app')
@section('body-class', '')

@section('title', __('panel/menu.order_returns'))

@section('content')
  <div class="card h-min-600">
    <div class="card-body">
      <x-panel-criteria :criteria="$criteria ?? []" :action="panel_route('order_returns.index')"/>
      @if ($order_returns->count())
        <div class="table-responsive">
          <table class="table align-middle">
            <thead>
            <tr>
              <td>{{ __('panel/common.id') }}</td>
              <td>{{ __('panel/order_return.customer') }}</td>
              <td>{{ __('front/return.number') }}</td>
              <td>{{ __('panel/order_return.order_number') }}</td>
              <td>{{ __('front/return.product_name') }}</td>
              <td>{{ __('front/return.opened') }}</td>
              <td>{{ __('front/return.status') }}</td>
              <td>{{ __('front/return.quantity') }}</td>
              <td>{{ __('panel/common.actions') }}</td>
            </tr>
            </thead>
            <tbody>

            @foreach($order_returns as $item)
              <tr>
                <td>{{ $item->id }}</td>
                <td>
                  <a href="{{ panel_route('customers.edit', $item->customer_id) }}" target="_blank">{{ $item->customer->name }}</a> <br/>
                  {{ $item->customer->email }} <br/>
                </td>
                <td>{{ $item->number }}</td>
                <td><a href="{{ panel_route('orders.edit', $item->order_id) }}" target="_blank">{{ $item->order_number }}</a></td>
                <td>{{ $item->product_name }}</td>
                <td>{{ $item->opened ? __('front/common.yes') : __('front/common.no') }}</td>
                <td>{{ $item->status_format }}</td>
                <td>{{ $item->quantity }}</td>
                <td>
                  <a href="{{ panel_route('order_returns.edit', [$item->id]) }}"
                     class="btn btn-sm btn-outline-primary">{{ __('panel/common.view')}}</a>
                  <form action="{{ panel_route('order_returns.destroy', [$item->id]) }}" method="POST" class="d-inline">
                    @csrf

                  </form>
                </td>
              </tr>
            @endforeach
            </tbody>
          </table>
        </div>
        {{ $order_returns->withQueryString()->links('panel::vendor/pagination/bootstrap-4') }}
      @else
        <x-common-no-data/>
      @endif
    </div>
  </div>
@endsection
@push('footer')
  <script>
  </script>
@endpush

innopacks/panel/resources/views/products/index.blade.php
@extends('panel::layouts.app')
@section('body-class', 'page-product')
@section('title', __('panel/menu.products'))

@section('page-title-right')
<a href="{{ panel_route('products.create') }}" class="btn btn-primary"><i class="bi bi-plus-square"></i> {{
  __('panel/common.create') }}</a>
@endsection

@section('content')
<div class="card h-min-600 " id="app">
  <div class="card-body">

    <x-panel-criteria :criteria="$criteria ?? []" :action="panel_route('products.index')" />

    @if ($products->count())
    <div class="table-responsive">
      <table class="table align-middle">
        <thead>
          <tr>
            <th>{{ __('panel/common.id') }}</th>
            <th class="wp-100">{{ __('panel/common.image') }}</th>
            <th>{{ __('panel/common.name') }}</th>
            <th>{{ __('panel/product.price') }}</th>
            <th>{{ __('panel/product.quantity') }}</th>
            <th>{{ __('panel/common.created_at') }}</th>
            <th>{{ __('panel/common.active') }}</th>
            <th>{{ __('panel/common.actions') }}</th>
          </tr>
        </thead>
        <tbody>
          @foreach ($products as $product)
          <tr>
            <td>{{ $product->id }}</td>
            <td>
              <div class="d-flex align-items-center justify-content-center wh-50 border">
                <a href="{{ $product->url }}" target="_blank">
                  <img src="{{ image_resize($product->images->first()->path ?? '') }}" class="img-fluid"
                    alt="{{ $product->translation->name ?? '' }}">
                </a>
              </div>
            </td>
            <td><a href="{{ $product->url }}" class="text-decoration-none" target="_blank">{{
                $product->translation->name ?? '' }}</a>
              @if($product->isMultiple()) &nbsp;<span class="text-bg-success px-1">M</span>@endif
            </td>
            <td>{{ currency_format($product->masterSku->price ?? 0) }}</td>
            <td>{{ $product->masterSku->quantity ?? 0 }}</td>
            <td>{{ $product->created_at }}</td>
            <td>@include('panel::shared.list_switch', ['value' => $product->active, 'url' =>
              panel_route('products.active', $product->id)])</td>
            <td>
              <div class="d-flex gap-2">
                <div>
                  <a href="{{ panel_route('products.edit', [$product->id]) }}">
                    <el-button size="small" plain type="primary">{{
                      __('panel/common.edit')}}</el-button>
                  </a>
                </div>
                <div>
                  <a href="{{ panel_route('products.copy', [$product->id]) }}">
                    <el-button size="small" plain type="warning">{{
                      __('panel/common.copy')}}</el-button>
                  </a>
                </div>
                <div>
                  <form ref="deleteForm" action="{{ panel_route('products.destroy', [$product->id]) }}" method="POST"
                    class="d-inline">
                    @csrf
                    @method('DELETE')
                    <el-button size="small" type="danger" plain @click="open({{$product->id}})">{{
                      __('panel/common.delete')}}</el-button>
                  </form>
                </div>
              </div>
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
    {{ $products->withQueryString()->links('panel::vendor/pagination/bootstrap-4') }}
    @else
    <x-common-no-data />
    @endif
  </div>
</div>
@endsection

@push('footer')
<script>
  const { createApp, ref } = Vue;
     const { ElMessageBox, ElMessage } = ElementPlus;

     const app = createApp({
     setup() {
     const deleteForm = ref(null); 

     const open = (index) => {
     ElMessageBox.confirm(
       '{{ __("common/base.hint_delete") }}',
       '{{ __("common/base.cancel") }}',
       {
         confirmButtonText: '{{ __("common/base.confirm")}}',
         cancelButtonText: '{{ __("common/base.cancel")}}',
         type: 'warning',
       }
       )
     .then(() => {
      const deleteUrl =urls.base_url+'/products/'+index;
      deleteForm.value.action=deleteUrl;
      deleteForm.value.submit(); 
      })
     .catch(() => {
     });
     };

     return { open, deleteForm }; 
       }
        });

     app.use(ElementPlus);
     app.mount('#app');
</script>
@endpush

innopacks/panel/resources/views/states/index.blade.php
@extends('panel::layouts.app')
@section('body-class', '')

@section('title', __('panel/menu.states'))

@push('header')
@endpush

@section('content')
<div class="card h-min-600" id="app">
  <div class="card-body">

    <x-panel-criteria :criteria="$criteria ?? []" :action="panel_route('states.index')" />

    @if ($states)
    <div class="table-responsive">
      <table class="table align-middle">
        <thead>
          <tr>
            <th>{{ __('panel/common.id') }}</th>
            <th>{{ __('panel/state.name') }}</th>
            <th>{{ __('panel/state.code') }}</th>
            <th>{{ __('panel/state.country_code') }}</th>
            <th>{{ __('panel/state.position') }}</th>
            <th>{{ __('panel/state.active') }}</th>
            <th>{{ __('panel/common.actions') }}</th>
          </tr>
        </thead>
        <tbody>
          @foreach($states as $item)
          <tr>
            <td>{{ $item['id'] }}</td>
            <td>{{ $item['name'] }}</td>
            <td>{{ $item['code'] }}</td>
            <td>{{ $item['country_code'] }}</td>
            <td>{{ $item['position'] }}</td>
            <td>
              @include('panel::shared.list_switch', ['value' => $item->active, 'url' => panel_route('states.active',
              $item->id)])
            </td>
            <td>
              <div class="d-flex gap-1">
                <el-button size="small" @click="edit({{ $item->id }})" plain type="primary">{{ __('panel/common.edit')}}
                </el-button>
                <form ref="deleteForm" action="{{ panel_route('states.destroy', [$item->id]) }}" method="POST"
                  class="d-inline">
                  @csrf
                  @method('DELETE')
                  <el-button size="small" type="danger" plain @click="open({{$item->id}})">{{
                    __('panel/common.delete')}}</el-button>
                </form>
              </div>
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
    {{ $states->withQueryString()->links('panel::vendor/pagination/bootstrap-4') }}
    @else
    <x-common-no-data />
    @endif
  </div>

  <el-drawer v-model="drawer" size="500" @close="close">
    <template #header>
      <div class="text-dark fs-4">{{ __('panel/menu.states') }}</div>
    </template>
    <el-form ref="formRef" label-position="top" :model="form" :rules="rules" label-width="auto" status-icon>
      <el-form-item label="{{ __('panel/common.name') }}" prop="name">
        <el-input v-model="form.name" placeholder="名称"></el-input>
      </el-form-item>

      <el-form-item label="编码" prop="code">
        <el-input v-model="form.code" placeholder="编码"></el-input>
      </el-form-item>

      <el-form-item label="国家代码" prop="country_id">
        <select v-model="form.country_id" class="form-control"
          @change="form.country_code = countries.find(item => item.id == form.country_id).code">
          <option v-for="item in countries" :value="item . id">@{{ item.name }}</option>
        </select>
      </el-form-item>

      <el-form-item label="排序" prop="position">
        <el-input v-model="form.position" placeholder="排序"></el-input>
      </el-form-item>

      <el-form-item label="状态" prop="active">
        <el-switch v-model="form.active" :active-value="1" :inactive-value="0"></el-switch>
      </el-form-item>
    </el-form>

    <template #footer>
      <div style="flex: auto">
        <el-button @click="drawer = false">{{ __('panel/common.close') }}</el-button>
        <el-button type="primary" @click="submit">{{ __('panel/common.btn_save') }}</el-button>
      </div>
    </template>
  </el-drawer>
</div>
@endsection
@push('footer')
<script>
  const api = @json(panel_route('states.index'));
  const { createApp, ref, reactive, onMounted, getCurrentInstance } = Vue;
  const { ElMessageBox, ElMessage } = ElementPlus;
  const listApp = createApp({
  setup() {
  const countries = ref([])
  const drawer = ref(false)
  const { proxy } = getCurrentInstance();
  const form = reactive({
  id: 0,
  name: '',
  code: '',
  country_code: '',
  country_id: '',
  position: '0',
  active: 1
  })

  const rules = {

  }

  onMounted(() => {
  getCountries()
  })

  const edit = (id) => {
  drawer.value = true
  axios.get(`${api}/${id}`).then((res) => {
  Object.keys(res).forEach(key => form.hasOwnProperty(key) && (form[key] = res[key]));
  })
  }

  const submit = () => {
  const url = form.id ? `${api}/${form.id}` : api
  const method = form.id ? 'put' : 'post'
  axios[method](url, form).then((res) => {
  drawer.value = false
  inno.msg(res.message)
  window.location.reload()
  })
  }

  const close = () => {
  proxy.$refs.formRef.resetFields()
  }

  const create = () => {
  drawer.value = true
  }

  const getCountries = () => {
  axios.get('{{ front_route('countries.index') }}').then(function(res) {
  countries.value = res.data;
  });
  }
  const deleteForm = ref(null);

  const open = (itemId) => {
    ElMessageBox.confirm(
    '{{ __("common/base.hint_delete") }}',
    '{{ __("common/base.cancel") }}',
    {
      confirmButtonText: '{{ __("common/base.confirm")}}',
      cancelButtonText: '{{ __("common/base.cancel")}}',
      type: 'warning',
    }
    )
  .then(() => {
  const deletUrl = urls.base_url + '/states/' + itemId;
  deleteForm.value.action = deletUrl;
  deleteForm.value.submit();
  })
  .catch(() => {

  });
  };
  const exportFuns = {
  drawer,
  form,
  edit,
  rules,
  close,
  submit,
  create,
  countries,
  deleteForm,
  open
  }

  window.app = exportFuns
  return exportFuns;
  }
  })

  listApp.use(ElementPlus);
  listApp.mount('#app');
</script>
@endpush